DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS users (
                                     user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email varchar NOT NULL,
                                     login varchar NOT NULL,
                                     name varchar,
                                     birthday date
);

CREATE TABLE IF NOT EXISTS mpa_rating (
                                          rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name char(5) NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
                                     film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar NOT NULL,
                                     description char(200),
    release_date date NOT NULL,
    duration integer NOT NULL,
    rating_id integer NOT NULL REFERENCES mpa_rating(rating_id)
    );

CREATE TABLE IF NOT EXISTS likes (
                                     like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     film_id integer NOT NULL REFERENCES films(film_id),
    user_id integer NOT NULL REFERENCES users(user_id)
    );

CREATE TABLE IF NOT EXISTS genres (
                                      genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id integer NOT NULL REFERENCES films(film_id),
    genre_id integer NOT NULL REFERENCES genres(genre_id),
    PRIMARY KEY(film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS user_friendships (
    sender_id integer NOT NULL REFERENCES users(user_id),
    recipient_id integer NOT NULL REFERENCES users(user_id),
    is_friend boolean NOT NULL,
    PRIMARY KEY(sender_id,recipient_id)
    );